<?php
/**
 * Plugin Name: WP Auto Poster
 * Plugin URI:  https://github.com/tahassafi/wp-ai-auto-poster
 * Description: Keyword-queue driven AI article publisher for WooCommerce shops. Each cron run consumes the oldest pending keyword, anchors the article to one real in-stock product chosen in code, writes it with the Anthropic Messages API, repairs and validates every link, and publishes a WordPress post with SEO metadata and a rotating cover image.
 * Version:     1.0.0
 * Author:      Taha Safi
 * License:     MIT
 * Requires PHP: 7.2
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'WPAP_VERSION', '1.0.0' );
define( 'WPAP_DIR', plugin_dir_path( __FILE__ ) );

require_once WPAP_DIR . 'config.php';
require_once WPAP_DIR . 'includes/db.php';
require_once WPAP_DIR . 'includes/generator.php';
require_once WPAP_DIR . 'includes/anchor.php';
require_once WPAP_DIR . 'includes/publisher.php';

if ( is_admin() ) {
	require_once WPAP_DIR . 'includes/admin.php';
}

register_activation_hook( __FILE__, 'wpap_activate' );

function wpap_activate() {
	wpap_install_tables();
	update_option( 'wpap_db_version', WPAP_VERSION );
}

/**
 * Creates the tables if the plugin folder was replaced by FTP/File Manager
 * without a deactivate/activate cycle.
 */
add_action( 'admin_init', function () {
	if ( get_option( 'wpap_db_version' ) !== WPAP_VERSION ) {
		wpap_install_tables();
		update_option( 'wpap_db_version', WPAP_VERSION );
	}
} );

/**
 * "Generated by AI Poster" flag in the posts list, so AI articles are
 * distinguishable from anything written by hand.
 */
add_filter( 'display_post_states', function ( $states, $post ) {
	if ( 'post' === $post->post_type && get_post_meta( $post->ID, '_wpap_keyword', true ) ) {
		$states['wpap'] = 'AI Poster';
	}
	return $states;
}, 10, 2 );
